/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.ChuyenDoi;
import DAO.DBConection;
import DTO.DTOPhieuNhap;
import DTO.MyCombobox;
import static GUI.pnlbanhang.jdcHanTraCongNo;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrator
 */
public class jdlThanhToanPhieu extends javax.swing.JDialog {

    /**
     * Creates new form jdlThanhToanPhieu
     */
    public jdlThanhToanPhieu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblSoPhieuNhap.setText(GUI.pnlthemphieunhap.txtMaDonNhapHang.getText());
        txtTienHang2.setText(pnlthemphieunhap.txtTongtien.getText());
        txtTienThue2.setText("0");
        txtTongCong2.setText(txtTienHang2.getText());
        jdcHanTraCongNo1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChucNang2 = new javax.swing.JPanel();
        lblSoLuong2 = new javax.swing.JLabel();
        lblGhiChu15 = new javax.swing.JLabel();
        txtTienHang2 = new javax.swing.JTextField();
        jFileChooser3 = new javax.swing.JFileChooser();
        cbbPhuongThuc2 = new javax.swing.JComboBox<>();
        txtThanhToan2 = new javax.swing.JTextField();
        lblGhiChu17 = new javax.swing.JLabel();
        lblGhiChu18 = new javax.swing.JLabel();
        txtTienThue2 = new javax.swing.JTextField();
        txtTongCong2 = new javax.swing.JTextField();
        lblGhiChu19 = new javax.swing.JLabel();
        lblGhiChu20 = new javax.swing.JLabel();
        lblGhiChu21 = new javax.swing.JLabel();
        txtTienThua1 = new javax.swing.JTextField();
        lblGhiChu22 = new javax.swing.JLabel();
        txtNo3 = new javax.swing.JTextField();
        lblGhiChu23 = new javax.swing.JLabel();
        jdcHanTraCongNo1 = new com.toedter.calendar.JDateChooser();
        pnlButton = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblSoPhieuNhap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlChucNang2.setBackground(new java.awt.Color(153, 153, 153));
        pnlChucNang2.setForeground(new java.awt.Color(255, 255, 255));
        pnlChucNang2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnlChucNangFocusGained(evt);
            }
        });

        lblSoLuong2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSoLuong2.setForeground(new java.awt.Color(255, 255, 255));
        lblSoLuong2.setText("Phương Thức Thanh Toán");

        lblGhiChu15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGhiChu15.setForeground(new java.awt.Color(255, 255, 255));
        lblGhiChu15.setText("Tiền Thuế");

        txtTienHang2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTienHang2.setEnabled(false);
        txtTienHang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienHangActionPerformed(evt);
            }
        });
        txtTienHang2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienHangKeyReleased(evt);
            }
        });

        jFileChooser3.setPreferredSize(new java.awt.Dimension(0, 0));

        cbbPhuongThuc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền Mặt", "Quẹt Thẻ", "Chuyển Khoản", "COD", " " }));

        txtThanhToan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtThanhToan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThanhToanActionPerformed(evt);
            }
        });
        txtThanhToan2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtThanhToanKeyReleased(evt);
            }
        });

        lblGhiChu17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGhiChu17.setForeground(new java.awt.Color(255, 255, 255));

        lblGhiChu18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGhiChu18.setForeground(new java.awt.Color(255, 255, 255));
        lblGhiChu18.setText("Tiền Hàng");

        txtTienThue2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTienThue2.setEnabled(false);
        txtTienThue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienThueActionPerformed(evt);
            }
        });
        txtTienThue2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienThueKeyReleased(evt);
            }
        });

        txtTongCong2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTongCong2.setEnabled(false);
        txtTongCong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongCongActionPerformed(evt);
            }
        });
        txtTongCong2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTongCongKeyReleased(evt);
            }
        });

        lblGhiChu19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGhiChu19.setForeground(new java.awt.Color(255, 255, 255));
        lblGhiChu19.setText("Tổng Cộng");

        lblGhiChu20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGhiChu20.setForeground(new java.awt.Color(255, 255, 255));
        lblGhiChu20.setText("Thanh Toán");

        lblGhiChu21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGhiChu21.setForeground(new java.awt.Color(255, 255, 255));
        lblGhiChu21.setText("Tiền Thừa");

        txtTienThua1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTienThua1.setEnabled(false);
        txtTienThua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienThua1ActionPerformed(evt);
            }
        });
        txtTienThua1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienThua1KeyReleased(evt);
            }
        });

        lblGhiChu22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGhiChu22.setForeground(new java.awt.Color(255, 255, 255));
        lblGhiChu22.setText("Nợ");

        txtNo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNo3.setEnabled(false);
        txtNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNo3ActionPerformed(evt);
            }
        });
        txtNo3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo3KeyReleased(evt);
            }
        });

        lblGhiChu23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGhiChu23.setForeground(new java.awt.Color(255, 255, 255));
        lblGhiChu23.setText("Hạn Trả");

        jdcHanTraCongNo1.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout pnlChucNang2Layout = new javax.swing.GroupLayout(pnlChucNang2);
        pnlChucNang2.setLayout(pnlChucNang2Layout);
        pnlChucNang2Layout.setHorizontalGroup(
            pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNang2Layout.createSequentialGroup()
                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChucNang2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChucNang2Layout.createSequentialGroup()
                                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlChucNang2Layout.createSequentialGroup()
                                        .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSoLuong2)
                                            .addComponent(lblGhiChu18)
                                            .addComponent(lblGhiChu15))
                                        .addGap(34, 34, 34)
                                        .addComponent(lblGhiChu17))
                                    .addComponent(lblGhiChu19)
                                    .addComponent(lblGhiChu20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTienThue2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTienHang2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbPhuongThuc2, javax.swing.GroupLayout.Alignment.LEADING, 0, 159, Short.MAX_VALUE)
                                    .addComponent(txtTongCong2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtThanhToan2, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlChucNang2Layout.createSequentialGroup()
                                    .addComponent(lblGhiChu21)
                                    .addGap(138, 138, 138)
                                    .addComponent(txtTienThua1))
                                .addGroup(pnlChucNang2Layout.createSequentialGroup()
                                    .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblGhiChu22)
                                        .addComponent(lblGhiChu23))
                                    .addGap(151, 151, 151)
                                    .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNo3)
                                        .addComponent(jdcHanTraCongNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(pnlChucNang2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jFileChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        pnlChucNang2Layout.setVerticalGroup(
            pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNang2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuong2)
                    .addComponent(cbbPhuongThuc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGhiChu17)
                    .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTienHang2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGhiChu18)))
                .addGap(34, 34, 34)
                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhiChu15)
                    .addComponent(txtTienThue2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhiChu19)
                    .addComponent(txtTongCong2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhiChu20)
                    .addComponent(txtThanhToan2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhiChu21)
                    .addComponent(txtTienThua1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhiChu22)
                    .addComponent(txtNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlChucNang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGhiChu23)
                    .addComponent(jdcHanTraCongNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jFileChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pnlButton.setBackground(new java.awt.Color(153, 153, 153));

        btnOK.setBackground(new java.awt.Color(204, 255, 204));
        btnOK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOK.setForeground(new java.awt.Color(0, 153, 0));
        btnOK.setText("Thanh Toán");
        btnOK.setToolTipText("");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnThoat)
                .addGap(67, 67, 67)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnThoat))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlTitle.setBackground(new java.awt.Color(153, 153, 153));
        pnlTitle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(63, 0, 4), null, null));
        pnlTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTitleMouseDragged(evt);
            }
        });
        pnlTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTitleMousePressed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(212, 216, 225));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Thông tin thanh toán cho đơn");

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(36, 36, 36))
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSoPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblSoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlChucNang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlChucNang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String SoPhieuNhap = lblSoPhieuNhap.getText();
        String ThanhToan;
        ThanhToan = "Đã Thanh Toán";
        double CongNo = ChuyenDoi.ChuyenSangSo(txtNo3.getText());
        String HinhThucThanhToan = cbbPhuongThuc2.getSelectedItem().toString();

        String HanTraCongNo;
        if (jdcHanTraCongNo1 == null) {
            HanTraCongNo = "0000-00-00";
        } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
            HanTraCongNo = sdf.format(jdcHanTraCongNo1.getDate());
        }
        DTOPhieuNhap PN = new DTOPhieuNhap(SoPhieuNhap, HinhThucThanhToan, ThanhToan, CongNo, HanTraCongNo);
        BLL.BLLPhieuNhap.SuaThanhToanPN(PN);
        MyCombobox mb = (MyCombobox) pnlthemphieunhap.cbbNhaCungCap.getSelectedItem();
        int MaNCC = (int) mb.Value;
        DTO.DTONhaCungCap ncc = BLL.BLLNhaCungCap.GetMaNCC(MaNCC);
        double CongNoBang = ncc.getCongNo();
        double CongNoSua = CongNoBang + CongNo;
        DTO.DTONhaCungCap sncc = new DTO.DTONhaCungCap(MaNCC, CongNoSua);
        BLL.BLLNhaCungCap.SuaCongNoNCC(sncc);
        ThongBaoCanhBao.ThongBao("Thanh toán thành công", "Thông Báo");
        pnlthemphieunhap.btnThanhToan.setEnabled(false);
        int ketquasaukhibam = JOptionPane.showConfirmDialog(new JFrame(),
                "Bạn Có Muốn In Hóa Đơn Phiếu Nhập Không ?", //thông báo
                "Thông Báo !", //tiêu đề
                JOptionPane.YES_NO_OPTION, //lựa chọn
                JOptionPane.ERROR_MESSAGE); // icon

        if (ketquasaukhibam == JOptionPane.YES_OPTION) {
            try {
                JasperReport report = JasperCompileManager.compileReport("src/Report/HoaDonPhieuNhap.jrxml");
                Hashtable map = new Hashtable();
                map.put("ID", SoPhieuNhap);
                map.put("duongdan", new File("").getCanonicalPath() + "\\");
                JasperPrint print = JasperFillManager.fillReport(report, map, DBConection.conn);

                JasperViewer jv = new JasperViewer(print, false);
                jv.setVisible(true);
                JasperViewer.viewReport(print, false);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

    }//GEN-LAST:event_jLabel10MouseClicked

    private void pnlTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitleMouseDragged

    }//GEN-LAST:event_pnlTitleMouseDragged

    private void pnlTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitleMousePressed

    }//GEN-LAST:event_pnlTitleMousePressed

    private void pnlChucNangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlChucNangFocusGained

    }//GEN-LAST:event_pnlChucNangFocusGained

    private void txtTongCongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTongCongKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongCongKeyReleased

    private void txtTongCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongCongActionPerformed

    private void txtTienThueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienThueKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienThueKeyReleased

    private void txtTienThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienThueActionPerformed

    private void txtThanhToanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThanhToanKeyReleased
        double TienTra, TongTien, No, TienThua;

        TongTien = BLL.ChuyenDoi.ChuyenTien(pnlthemphieunhap.txtTongtien.getText());
        TienTra = BLL.ChuyenDoi.ChuyenTien(txtThanhToan2.getText());

        txtThanhToan2.setText(BLL.ChuyenDoi.DinhDangTien(TienTra));
        TienThua = TienTra - TongTien;
        No = TongTien - TienTra;

        txtNo3.setText(BLL.ChuyenDoi.DinhDangTien(No));
        txtTienThua1.setText(ChuyenDoi.DinhDangTien(TienThua));
        if (TienTra > TongTien) {
            txtNo3.setText("0");
            jdcHanTraCongNo1.setEnabled(false);
            jdcHanTraCongNo1.setDate(null);
        }
        if (TienTra < TongTien) {
            txtTienThua1.setText("0");
            jdcHanTraCongNo1.setEnabled(true);
            Date date = new Date();
            jdcHanTraCongNo1.setDate(date);
        }
    }//GEN-LAST:event_txtThanhToanKeyReleased

    private void txtThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThanhToanActionPerformed

    private void txtTienHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienHangKeyReleased

    }//GEN-LAST:event_txtTienHangKeyReleased

    private void txtTienHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienHangActionPerformed

    private void txtTienThua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienThua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienThua1ActionPerformed

    private void txtTienThua1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienThua1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienThua1KeyReleased

    private void txtNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNo3ActionPerformed

    private void txtNo3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNo3KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlThanhToanPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlThanhToanPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlThanhToanPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlThanhToanPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlThanhToanPhieu dialog = new jdlThanhToanPhieu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbbPhuongThuc2;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JLabel jLabel10;
    private com.toedter.calendar.JDateChooser jdcHanTraCongNo1;
    private javax.swing.JLabel lblGhiChu15;
    private javax.swing.JLabel lblGhiChu17;
    private javax.swing.JLabel lblGhiChu18;
    private javax.swing.JLabel lblGhiChu19;
    private javax.swing.JLabel lblGhiChu20;
    private javax.swing.JLabel lblGhiChu21;
    private javax.swing.JLabel lblGhiChu22;
    private javax.swing.JLabel lblGhiChu23;
    private javax.swing.JLabel lblSoLuong2;
    private javax.swing.JLabel lblSoPhieuNhap;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlChucNang2;
    private javax.swing.JPanel pnlTitle;
    public static javax.swing.JTextField txtNo3;
    public static javax.swing.JTextField txtThanhToan2;
    public static javax.swing.JTextField txtTienHang2;
    public static javax.swing.JTextField txtTienThua1;
    public static javax.swing.JTextField txtTienThue2;
    public static javax.swing.JTextField txtTongCong2;
    // End of variables declaration//GEN-END:variables
}
